GET http://localhost:3000/

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "abdo_osama22234sd",
  "password": "abdo_Osama222",
  "email": "abdo_osama2232a@gmail.com",
  "name": "abdo_osama222"
  
}

###
POST http://localhost:3000/auth/localLogin
Content-Type: application/json

{
  "username": "abdo_osama222",
  "password": "abdo_Osama222"
  
}
###(just try in browser)must be logged in as admin to add a product
POST http://localhost:3000/admin/addProduct
Content-Type: application/json

{
  "title": "test product",
  "details": "test product description",
  "price": 100,
  "category": "test category"
}

###(just try in browser)must be logged in as admin to add a product
GET http://localhost:3000/admin/getProducts?page=1

####
GET http://localhost:3000/admin/getProductById?id=680588d2e9ffa84d37b2516e


###
PATCH  http://localhost:3000/admin/editProduct?id=680588d2e9ffa84d37b2516e
Content-Type: application/json

{
  "title": "test product",
  "details": "test product description",
  "price": "1101",
  "category": "test category"
}




### Get Products with Cookie
GET http://localhost:3000/admin/getProducts
cookies: